In [1]:
from pynwb import NWBHDF5IO
#import nwbwidgets as nw

io = NWBHDF5IO("S9_DAS.nwb", "r")
nwb = io.read()

#table
print("-------------Trial Table-----------")
trials_df = nwb.trials.to_dataframe()
trials_df["true_duration_s"] = trials_df["stop_time"] / 60
trials_df

-------------Trial Table-----------

,start_time,stop_time,dataset,attended_ear,stim_L_name,stim_R_name,n_speakers,attend_mf,attend_lr,stim_male_name,stim_female_name,trigger,acoustic_condition,start_sample,stop_sample,true_duration_s
id,,,,,,,,,,,,,,,,
0,0.0,389.0,DAS,R,part1_track2_dry.wav,part1_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.483333
1,0.0,391.0,DAS,L,part2_track1_dry.wav,part2_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.516667
2,0.0,389.0,DAS,R,part3_track2_dry.wav,part3_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.483333
3,0.0,399.0,DAS,L,part4_track1_dry.wav,part4_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.650000
4,0.0,389.0,DAS,R,part1_track1_dry.wav,part1_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.483333
5,0.0,391.0,DAS,L,part2_track2_dry.wav,part2_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.516667
6,0.0,389.0,DAS,R,part3_track1_dry.wav,part3_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.483333
7,0.0,399.0,DAS,L,part4_track2_dry.wav,part4_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,6.650000
8,0.0,124.0,DAS,R,rep_part1_track2_dry.wav,rep_part1_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
9,0.0,124.0,DAS,L,rep_part2_track1_dry.wav,rep_part2_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
10,0.0,124.0,DAS,R,rep_part3_track2_dry.wav,rep_part3_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
11,0.0,124.0,DAS,L,rep_part4_track1_dry.wav,rep_part4_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
12,0.0,124.0,DAS,R,rep_part1_track2_dry.wav,rep_part1_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
13,0.0,124.0,DAS,L,rep_part2_track1_dry.wav,rep_part2_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
14,0.0,124.0,DAS,R,rep_part3_track2_dry.wav,rep_part3_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
15,0.0,124.0,DAS,L,rep_part4_track1_dry.wav,rep_part4_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
16,0.0,124.0,DAS,R,rep_part1_track2_dry.wav,rep_part1_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
17,0.0,124.0,DAS,L,rep_part2_track1_dry.wav,rep_part2_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
18,0.0,124.0,DAS,R,rep_part3_track2_dry.wav,rep_part3_track1_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667
19,0.0,124.0,DAS,L,rep_part4_track1_dry.wav,rep_part4_track2_dry.wav,2,-1,-1,,,-1,-1,-1,-1,2.066667

In [2]:
#raw eeg
print("-------------Raw EEG of 1 trial-----------")

raw = nwb.acquisition["trial_10_EEG_raw"]
print(raw)
print("shape:", raw.data.shape)
print("fs:", raw.rate)

-------------Raw EEG of 1 trial-----------
trial_10_EEG_raw pynwb.base.TimeSeries at 0x139976484037312
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (15872, 64), type "<f8">
  description: Raw EEG signal
  offset: 0.0
  rate: 128.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: microvolts

shape: (15872, 64)
fs: 128.0

In [3]:
#preprocessed EEG
print("---------------EEGPP-------------")
eeg_proc = nwb.processing["eeg_preprocessed"]
pp = eeg_proc.data_interfaces["trial_10_EEG_preprocessed"]
print(pp)
print("shape:", pp.data.shape)
print("fs:", pp.rate)

---------------EEGPP-------------
trial_10_EEG_preprocessed pynwb.ecephys.ElectricalSeries at 0x139976484039328
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (3968, 64), type "<f8">
  description: Preprocessed EEG
  electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
  offset: 0.0
  rate: 32.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: volts

shape: (3968, 64)
fs: 32.0

In [4]:
#electrode metadata
elec_df = nwb.electrodes.to_dataframe()
elec_df

,location,group,label,group_name,x,y,z,imp
id,,,,,,,,
0,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,1,EEG_group,NaN,NaN,NaN,NaN
1,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,2,EEG_group,NaN,NaN,NaN,NaN
2,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,3,EEG_group,NaN,NaN,NaN,NaN
3,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,4,EEG_group,NaN,NaN,NaN,NaN
4,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,5,EEG_group,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
59,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,60,EEG_group,NaN,NaN,NaN,NaN
60,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,61,EEG_group,NaN,NaN,NaN,NaN
61,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,62,EEG_group,NaN,NaN,NaN,NaN
62,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,63,EEG_group,NaN,NaN,NaN,NaN
63,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x13...,64,EEG_group,NaN,NaN,NaN,NaN

In [5]:
import re

eeg_proc = nwb.processing["eeg_preprocessed"]

def tid_from_key(k):
    m = re.match(r"trial_(\d+)_EEG_preprocessed$", k)
    return int(m.group(1)) if m else None

keys = sorted(eeg_proc.data_interfaces.keys(), key=lambda k: tid_from_key(k) or 10**9)

for k in keys:
    ts = eeg_proc.data_interfaces[k]
    tid = tid_from_key(k)
    dur = ts.data.shape[0] / ts.rate
    print(tid, k, ts.data.shape, dur)

1 trial_1_EEG_preprocessed (12448, 64) 389.0
2 trial_2_EEG_preprocessed (12512, 64) 391.0
3 trial_3_EEG_preprocessed (12448, 64) 389.0
4 trial_4_EEG_preprocessed (12768, 64) 399.0
5 trial_5_EEG_preprocessed (12448, 64) 389.0
6 trial_6_EEG_preprocessed (12512, 64) 391.0
7 trial_7_EEG_preprocessed (12448, 64) 389.0
8 trial_8_EEG_preprocessed (12768, 64) 399.0
9 trial_9_EEG_preprocessed (3968, 64) 124.0
10 trial_10_EEG_preprocessed (3968, 64) 124.0
11 trial_11_EEG_preprocessed (3968, 64) 124.0
12 trial_12_EEG_preprocessed (3968, 64) 124.0
13 trial_13_EEG_preprocessed (3968, 64) 124.0
14 trial_14_EEG_preprocessed (3968, 64) 124.0
15 trial_15_EEG_preprocessed (3968, 64) 124.0
16 trial_16_EEG_preprocessed (3968, 64) 124.0
17 trial_17_EEG_preprocessed (3968, 64) 124.0
18 trial_18_EEG_preprocessed (3968, 64) 124.0
19 trial_19_EEG_preprocessed (3968, 64) 124.0
20 trial_20_EEG_preprocessed (3968, 64) 124.0